# Generated by Django 5.2.7 on 2025-10-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item',
            new_name='cart',
        ),
    ]
