# Generated by Django 5.2.7 on 2025-10-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cart_item_cartitem_cart'),
        ('products', '0010_alter_product_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('billing_first_name', models.CharField(max_length=50)),
                ('billing_last_name', models.CharField(max_length=50)),
                ('billing_company', models.CharField(blank=True, max_length=100)),
                ('billing_phone', models.CharField(max_length=15)),
                ('billing_email', models.EmailField(max_length=50)),
                ('billing_address', models.CharField(max_length=250)),
                ('billing_country', models.CharField(max_length=50)),
                ('billing_state', models.CharField(max_length=50)),
                ('billing_city', models.CharField(max_length=50)),
                ('shipping_first_name', models.CharField(max_length=50)),
                ('shipping_last_name', models.CharField(max_length=50)),
                ('shipping_company', models.CharField(blank=True, max_length=100)),
                ('shipping_phone', models.CharField(max_length=15)),
                ('shipping_email', models.EmailField(max_length=50)),
                ('shipping_address', models.CharField(max_length=250)),
                ('shipping_country', models.CharField(max_length=50)),
                ('shipping_state', models.CharField(max_length=50)),
                ('shipping_city', models.CharField(max_length=50)),
                ('order_note', models.TextField(blank=True, max_length=200)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
