# Generated by Django 5.2.7 on 2025-10-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_order_id_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(default='rexbmxbikecollection@gmail.com', max_length=50),
        ),
    ]
