# Generated by Django 5.2.7 on 2025-10-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_billing_address_alter_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(blank=True, default='101 Duval street, Key West, FL 33040', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, default='Key West', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_company',
            field=models.CharField(blank=True, default='Rexbmx Bike Collection', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, default='rexbmxbikecollection@gmail.com', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(blank=True, default='0123456789', max_length=15, null=True),
        ),
    ]
