# Generated by Django 5.2.7 on 2025-10-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_billing_address_alter_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='Cash on Delivery', max_length=100, null=True),
        ),
    ]
