# Generated by Django 5.2.7 on 2025-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times this coupon can be used.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
