# Generated by Django 5.2.7 on 2025-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='media/slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/slider/'),
        ),
    ]
