# Generated by Django 5.2.7 on 2025-10-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_color_product_parts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
    ]
