# Generated by Django 5.2.7 on 2025-10-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_slug_category_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
