# Generated by Django 5.2.7 on 2025-10-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoty_name',
            new_name='category_name',
        ),
    ]
