# Generated by Django 5.2.7 on 2025-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_color_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
